language: cpp
addons:
    apt:
        packages:
           - python3
           - python3-pip
           - ninja-build
install:
    - pip3 install --user --upgrade pip
    - pip3 install --user meson
script:
    - meson build
    - cd build
    - ninja
    - ninja test